### ISSUE TITLE
Installing builds from a stale generated project and reports the symptom

### ISSUE THREAD

**Issue by danwright32** [danwright32/ovation#390]
`Ovation.xcodeproj` is generated from `project.yml` and gitignored. `scripts/build-install.sh` builds whatever project happens to be in the checkout, without asking whether it is current.

Measured 2026-09-17, immediately after merging ovation#319: the install failed with `cannot find type 'InvoiceFooterSetting' in scope` across four files, plus a wall of SwiftCompile output. The code was fine and main was green; the checkout's generated project simply predated the merge and did not list the new file. `bash scripts/regenerate-xcode-project.sh` fixed it and the install then took 26 seconds.

Why it matters: the message names the symptom and not the missing step, which is the same shape as ovation#373 at a different entry point. It is worst exactly when it is most likely, which is right after pulling merged work, because that is when a file has most recently been added. The repository already owns the answer: `scripts/check-xcode-project-current.sh` decides this question, the push gate runs it, and `built_product_remedy` already knows the sentence to print for a project that is stale or absent.

Rough direction: have `build-install.sh` ask that check before it builds, and either regenerate (the project is a derived artifact, so regenerating is not a decision anybody needs to make) or refuse by name with the command to run. Whichever, the refusal should come from the same place the bundle suites take theirs, so the two cannot give different advice for one fault (L70).
